### ISSUE TITLE
How do you create projects?

### ISSUE THREAD

**Issue by jakefb** [TolgaTatli/Moon#119] opened 2017-05-05 03:21 UTC
Hi I have a question, how do you create a project?

Thanks in advance!

**Comment by dale6998** [comment] 2018-04-15 17:07
Duplicate of [#79](https://github.com/TaylanTatli/Moon/issues?utf8=%E2%9C%93&q=project).

You have to add `project: true` to the post header.  Post your posts in the usual place...no special folders named "project" or anything like that.

**Closed** 2024-09-14 17:39 UTC

**Comment by wanlinjuan** [comment] 2025-07-31 15:39
> Duplicate of [#79](https://github.com/TaylanTatli/Moon/issues?utf8=%E2%9C%93&q=project).
> 
> You have to add `project: true` to the post header. Post your posts in the usual place...no special folders named "project" or anything like that.

Thank you so much for your help!
